apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: z9ts1z3ao-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/z9ts1z3ao-dotnet-basic-gitops